# Generated by Django 5.0.3 on 2024-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_detail',
            name='about',
            field=models.CharField(default='a', max_length=300),
        ),
    ]
