# Generated by Django 5.0.3 on 2024-09-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0002_teacher_detail_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_detail',
            name='image',
            field=models.ImageField(upload_to='staff/'),
        ),
    ]
