# Generated by Django 5.0.3 on 2025-03-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
